requires 'Rose::Object';
requires 'Rose::DateTime';
requires 'Rose::DB';
requires 'Rose::DB::Object::Manager';
requires 'XML::Writer';
requires 'Readonly';
requires 'Modern::Perl';
requires 'Exporter::Auto';
requires 'Log::Log4perl';