create table %MART_NAME%.TEMP0 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_0 on %MART_NAME%.TEMP0(child_term_id_301);
create table %MART_NAME%.TEMP1 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP0 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP0;
create index I_1 on %MART_NAME%.TEMP1(ontology_id_305);
create table %MART_NAME%.TEMP2 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP1 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='BFO';
drop table %MART_NAME%.TEMP1;
create index I_2 on %MART_NAME%.TEMP2(parent_term_id_301);
create table %MART_NAME%.TEMP3 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP2 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP2;
create index I_3 on %MART_NAME%.TEMP3(ontology_id_305_r1);
create table %MART_NAME%.TEMP4 as select a.* from %MART_NAME%.TEMP3 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='BFO';
drop table %MART_NAME%.TEMP3;
create index I_4 on %MART_NAME%.TEMP4(subparent_term_id_301);
create table %MART_NAME%.TEMP5 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP4 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP4;
create index I_5 on %MART_NAME%.TEMP5(ontology_id_305_r2);
create table %MART_NAME%.TEMP6 as select a.* from %MART_NAME%.TEMP5 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='BFO';
drop table %MART_NAME%.TEMP5;
create table %MART_NAME%.TEMP7 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP6;
drop table %MART_NAME%.TEMP6;
create index I_6 on %MART_NAME%.TEMP7(accession_305);
create index I_7 on %MART_NAME%.TEMP7(accession_305_r1);
rename table %MART_NAME%.TEMP7 to %MART_NAME%.closure_BFO__closure__main;
create index I_8 on %MART_NAME%.closure_BFO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP8 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_9 on %MART_NAME%.TEMP8(child_term_id_301);
create table %MART_NAME%.TEMP9 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP8 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP8;
create index I_10 on %MART_NAME%.TEMP9(ontology_id_305);
create table %MART_NAME%.TEMP10 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP9 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='BTO';
drop table %MART_NAME%.TEMP9;
create index I_11 on %MART_NAME%.TEMP10(parent_term_id_301);
create table %MART_NAME%.TEMP11 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP10 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP10;
create index I_12 on %MART_NAME%.TEMP11(ontology_id_305_r1);
create table %MART_NAME%.TEMP12 as select a.* from %MART_NAME%.TEMP11 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='BTO';
drop table %MART_NAME%.TEMP11;
create index I_13 on %MART_NAME%.TEMP12(subparent_term_id_301);
create table %MART_NAME%.TEMP13 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP12 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP12;
create index I_14 on %MART_NAME%.TEMP13(ontology_id_305_r2);
create table %MART_NAME%.TEMP14 as select a.* from %MART_NAME%.TEMP13 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='BTO';
drop table %MART_NAME%.TEMP13;
create table %MART_NAME%.TEMP15 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP14;
drop table %MART_NAME%.TEMP14;
create index I_15 on %MART_NAME%.TEMP15(accession_305);
create index I_16 on %MART_NAME%.TEMP15(accession_305_r1);
rename table %MART_NAME%.TEMP15 to %MART_NAME%.closure_BTO__closure__main;
create index I_17 on %MART_NAME%.closure_BTO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP16 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_18 on %MART_NAME%.TEMP16(child_term_id_301);
create table %MART_NAME%.TEMP17 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP16 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP16;
create index I_19 on %MART_NAME%.TEMP17(ontology_id_305);
create table %MART_NAME%.TEMP18 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP17 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='CHEBI';
drop table %MART_NAME%.TEMP17;
create index I_20 on %MART_NAME%.TEMP18(parent_term_id_301);
create table %MART_NAME%.TEMP19 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP18 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP18;
create index I_21 on %MART_NAME%.TEMP19(ontology_id_305_r1);
create table %MART_NAME%.TEMP20 as select a.* from %MART_NAME%.TEMP19 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='CHEBI';
drop table %MART_NAME%.TEMP19;
create index I_22 on %MART_NAME%.TEMP20(subparent_term_id_301);
create table %MART_NAME%.TEMP21 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP20 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP20;
create index I_23 on %MART_NAME%.TEMP21(ontology_id_305_r2);
create table %MART_NAME%.TEMP22 as select a.* from %MART_NAME%.TEMP21 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='CHEBI';
drop table %MART_NAME%.TEMP21;
create table %MART_NAME%.TEMP23 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP22;
drop table %MART_NAME%.TEMP22;
create index I_24 on %MART_NAME%.TEMP23(accession_305);
create index I_25 on %MART_NAME%.TEMP23(accession_305_r1);
rename table %MART_NAME%.TEMP23 to %MART_NAME%.closure_CHEBI__closure__main;
create index I_26 on %MART_NAME%.closure_CHEBI__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP24 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_27 on %MART_NAME%.TEMP24(child_term_id_301);
create table %MART_NAME%.TEMP25 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP24 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP24;
create index I_28 on %MART_NAME%.TEMP25(ontology_id_305);
create table %MART_NAME%.TEMP26 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP25 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='CL';
drop table %MART_NAME%.TEMP25;
create index I_29 on %MART_NAME%.TEMP26(parent_term_id_301);
create table %MART_NAME%.TEMP27 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP26 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP26;
create index I_30 on %MART_NAME%.TEMP27(ontology_id_305_r1);
create table %MART_NAME%.TEMP28 as select a.* from %MART_NAME%.TEMP27 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='CL';
drop table %MART_NAME%.TEMP27;
create index I_31 on %MART_NAME%.TEMP28(subparent_term_id_301);
create table %MART_NAME%.TEMP29 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP28 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP28;
create index I_32 on %MART_NAME%.TEMP29(ontology_id_305_r2);
create table %MART_NAME%.TEMP30 as select a.* from %MART_NAME%.TEMP29 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='CL';
drop table %MART_NAME%.TEMP29;
create table %MART_NAME%.TEMP31 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP30;
drop table %MART_NAME%.TEMP30;
create index I_33 on %MART_NAME%.TEMP31(accession_305);
create index I_34 on %MART_NAME%.TEMP31(accession_305_r1);
rename table %MART_NAME%.TEMP31 to %MART_NAME%.closure_CL__closure__main;
create index I_35 on %MART_NAME%.closure_CL__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP32 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_36 on %MART_NAME%.TEMP32(child_term_id_301);
create table %MART_NAME%.TEMP33 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP32 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP32;
create index I_37 on %MART_NAME%.TEMP33(ontology_id_305);
create table %MART_NAME%.TEMP34 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP33 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='ECO';
drop table %MART_NAME%.TEMP33;
create index I_38 on %MART_NAME%.TEMP34(parent_term_id_301);
create table %MART_NAME%.TEMP35 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP34 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP34;
create index I_39 on %MART_NAME%.TEMP35(ontology_id_305_r1);
create table %MART_NAME%.TEMP36 as select a.* from %MART_NAME%.TEMP35 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='ECO';
drop table %MART_NAME%.TEMP35;
create index I_40 on %MART_NAME%.TEMP36(subparent_term_id_301);
create table %MART_NAME%.TEMP37 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP36 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP36;
create index I_41 on %MART_NAME%.TEMP37(ontology_id_305_r2);
create table %MART_NAME%.TEMP38 as select a.* from %MART_NAME%.TEMP37 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='ECO';
drop table %MART_NAME%.TEMP37;
create table %MART_NAME%.TEMP39 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP38;
drop table %MART_NAME%.TEMP38;
create index I_42 on %MART_NAME%.TEMP39(accession_305);
create index I_43 on %MART_NAME%.TEMP39(accession_305_r1);
rename table %MART_NAME%.TEMP39 to %MART_NAME%.closure_ECO__closure__main;
create index I_44 on %MART_NAME%.closure_ECO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP40 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_45 on %MART_NAME%.TEMP40(child_term_id_301);
create table %MART_NAME%.TEMP41 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP40 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP40;
create index I_46 on %MART_NAME%.TEMP41(ontology_id_305);
create table %MART_NAME%.TEMP42 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP41 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='EFO';
drop table %MART_NAME%.TEMP41;
create index I_47 on %MART_NAME%.TEMP42(parent_term_id_301);
create table %MART_NAME%.TEMP43 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP42 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP42;
create index I_48 on %MART_NAME%.TEMP43(ontology_id_305_r1);
create table %MART_NAME%.TEMP44 as select a.* from %MART_NAME%.TEMP43 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='EFO';
drop table %MART_NAME%.TEMP43;
create index I_49 on %MART_NAME%.TEMP44(subparent_term_id_301);
create table %MART_NAME%.TEMP45 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP44 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP44;
create index I_50 on %MART_NAME%.TEMP45(ontology_id_305_r2);
create table %MART_NAME%.TEMP46 as select a.* from %MART_NAME%.TEMP45 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='EFO';
drop table %MART_NAME%.TEMP45;
create table %MART_NAME%.TEMP47 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP46;
drop table %MART_NAME%.TEMP46;
create index I_51 on %MART_NAME%.TEMP47(accession_305);
create index I_52 on %MART_NAME%.TEMP47(accession_305_r1);
rename table %MART_NAME%.TEMP47 to %MART_NAME%.closure_EFO__closure__main;
create index I_53 on %MART_NAME%.closure_EFO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP48 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_54 on %MART_NAME%.TEMP48(child_term_id_301);
create table %MART_NAME%.TEMP49 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP48 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP48;
create index I_55 on %MART_NAME%.TEMP49(ontology_id_305);
create table %MART_NAME%.TEMP50 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP49 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='EO';
drop table %MART_NAME%.TEMP49;
create index I_56 on %MART_NAME%.TEMP50(parent_term_id_301);
create table %MART_NAME%.TEMP51 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP50 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP50;
create index I_57 on %MART_NAME%.TEMP51(ontology_id_305_r1);
create table %MART_NAME%.TEMP52 as select a.* from %MART_NAME%.TEMP51 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='EO';
drop table %MART_NAME%.TEMP51;
create index I_58 on %MART_NAME%.TEMP52(subparent_term_id_301);
create table %MART_NAME%.TEMP53 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP52 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP52;
create index I_59 on %MART_NAME%.TEMP53(ontology_id_305_r2);
create table %MART_NAME%.TEMP54 as select a.* from %MART_NAME%.TEMP53 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='EO';
drop table %MART_NAME%.TEMP53;
create table %MART_NAME%.TEMP55 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP54;
drop table %MART_NAME%.TEMP54;
create index I_60 on %MART_NAME%.TEMP55(accession_305);
create index I_61 on %MART_NAME%.TEMP55(accession_305_r1);
rename table %MART_NAME%.TEMP55 to %MART_NAME%.closure_EO__closure__main;
create index I_62 on %MART_NAME%.closure_EO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP56 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_63 on %MART_NAME%.TEMP56(child_term_id_301);
create table %MART_NAME%.TEMP57 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP56 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP56;
create index I_64 on %MART_NAME%.TEMP57(ontology_id_305);
create table %MART_NAME%.TEMP58 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP57 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='FYPO';
drop table %MART_NAME%.TEMP57;
create index I_65 on %MART_NAME%.TEMP58(parent_term_id_301);
create table %MART_NAME%.TEMP59 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP58 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP58;
create index I_66 on %MART_NAME%.TEMP59(ontology_id_305_r1);
create table %MART_NAME%.TEMP60 as select a.* from %MART_NAME%.TEMP59 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='FYPO';
drop table %MART_NAME%.TEMP59;
create index I_67 on %MART_NAME%.TEMP60(subparent_term_id_301);
create table %MART_NAME%.TEMP61 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP60 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP60;
create index I_68 on %MART_NAME%.TEMP61(ontology_id_305_r2);
create table %MART_NAME%.TEMP62 as select a.* from %MART_NAME%.TEMP61 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='FYPO';
drop table %MART_NAME%.TEMP61;
create table %MART_NAME%.TEMP63 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP62;
drop table %MART_NAME%.TEMP62;
create index I_69 on %MART_NAME%.TEMP63(accession_305);
create index I_70 on %MART_NAME%.TEMP63(accession_305_r1);
rename table %MART_NAME%.TEMP63 to %MART_NAME%.closure_FYPO__closure__main;
create index I_71 on %MART_NAME%.closure_FYPO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP64 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_72 on %MART_NAME%.TEMP64(child_term_id_301);
create table %MART_NAME%.TEMP65 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP64 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP64;
create index I_73 on %MART_NAME%.TEMP65(ontology_id_305);
create table %MART_NAME%.TEMP66 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP65 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='FYPO_EXT';
drop table %MART_NAME%.TEMP65;
create index I_74 on %MART_NAME%.TEMP66(parent_term_id_301);
create table %MART_NAME%.TEMP67 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP66 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP66;
create index I_75 on %MART_NAME%.TEMP67(ontology_id_305_r1);
create table %MART_NAME%.TEMP68 as select a.* from %MART_NAME%.TEMP67 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='FYPO_EXT';
drop table %MART_NAME%.TEMP67;
create index I_76 on %MART_NAME%.TEMP68(subparent_term_id_301);
create table %MART_NAME%.TEMP69 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP68 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP68;
create index I_77 on %MART_NAME%.TEMP69(ontology_id_305_r2);
create table %MART_NAME%.TEMP70 as select a.* from %MART_NAME%.TEMP69 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='FYPO_EXT';
drop table %MART_NAME%.TEMP69;
create table %MART_NAME%.TEMP71 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP70;
drop table %MART_NAME%.TEMP70;
create index I_78 on %MART_NAME%.TEMP71(accession_305);
create index I_79 on %MART_NAME%.TEMP71(accession_305_r1);
rename table %MART_NAME%.TEMP71 to %MART_NAME%.closure_FYPO_EXT__closure__main;
create index I_80 on %MART_NAME%.closure_FYPO_EXT__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP72 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_81 on %MART_NAME%.TEMP72(child_term_id_301);
create table %MART_NAME%.TEMP73 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP72 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP72;
create index I_82 on %MART_NAME%.TEMP73(ontology_id_305);
create table %MART_NAME%.TEMP74 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP73 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='GO';
drop table %MART_NAME%.TEMP73;
create index I_83 on %MART_NAME%.TEMP74(parent_term_id_301);
create table %MART_NAME%.TEMP75 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP74 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP74;
create index I_84 on %MART_NAME%.TEMP75(ontology_id_305_r1);
create table %MART_NAME%.TEMP76 as select a.* from %MART_NAME%.TEMP75 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='GO';
drop table %MART_NAME%.TEMP75;
create index I_85 on %MART_NAME%.TEMP76(subparent_term_id_301);
create table %MART_NAME%.TEMP77 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP76 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP76;
create index I_86 on %MART_NAME%.TEMP77(ontology_id_305_r2);
create table %MART_NAME%.TEMP78 as select a.* from %MART_NAME%.TEMP77 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='GO';
drop table %MART_NAME%.TEMP77;
create table %MART_NAME%.TEMP79 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP78;
drop table %MART_NAME%.TEMP78;
create index I_87 on %MART_NAME%.TEMP79(accession_305);
create index I_88 on %MART_NAME%.TEMP79(accession_305_r1);
rename table %MART_NAME%.TEMP79 to %MART_NAME%.closure_GO__closure__main;
create index I_89 on %MART_NAME%.closure_GO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP80 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_90 on %MART_NAME%.TEMP80(child_term_id_301);
create table %MART_NAME%.TEMP81 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP80 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP80;
create index I_91 on %MART_NAME%.TEMP81(ontology_id_305);
create table %MART_NAME%.TEMP82 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP81 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='GRO';
drop table %MART_NAME%.TEMP81;
create index I_92 on %MART_NAME%.TEMP82(parent_term_id_301);
create table %MART_NAME%.TEMP83 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP82 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP82;
create index I_93 on %MART_NAME%.TEMP83(ontology_id_305_r1);
create table %MART_NAME%.TEMP84 as select a.* from %MART_NAME%.TEMP83 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='GRO';
drop table %MART_NAME%.TEMP83;
create index I_94 on %MART_NAME%.TEMP84(subparent_term_id_301);
create table %MART_NAME%.TEMP85 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP84 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP84;
create index I_95 on %MART_NAME%.TEMP85(ontology_id_305_r2);
create table %MART_NAME%.TEMP86 as select a.* from %MART_NAME%.TEMP85 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='GRO';
drop table %MART_NAME%.TEMP85;
create table %MART_NAME%.TEMP87 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP86;
drop table %MART_NAME%.TEMP86;
create index I_96 on %MART_NAME%.TEMP87(accession_305);
create index I_97 on %MART_NAME%.TEMP87(accession_305_r1);
rename table %MART_NAME%.TEMP87 to %MART_NAME%.closure_GRO__closure__main;
create index I_98 on %MART_NAME%.closure_GRO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP88 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_99 on %MART_NAME%.TEMP88(child_term_id_301);
create table %MART_NAME%.TEMP89 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP88 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP88;
create index I_100 on %MART_NAME%.TEMP89(ontology_id_305);
create table %MART_NAME%.TEMP90 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP89 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='MOD';
drop table %MART_NAME%.TEMP89;
create index I_101 on %MART_NAME%.TEMP90(parent_term_id_301);
create table %MART_NAME%.TEMP91 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP90 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP90;
create index I_102 on %MART_NAME%.TEMP91(ontology_id_305_r1);
create table %MART_NAME%.TEMP92 as select a.* from %MART_NAME%.TEMP91 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='MOD';
drop table %MART_NAME%.TEMP91;
create index I_103 on %MART_NAME%.TEMP92(subparent_term_id_301);
create table %MART_NAME%.TEMP93 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP92 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP92;
create index I_104 on %MART_NAME%.TEMP93(ontology_id_305_r2);
create table %MART_NAME%.TEMP94 as select a.* from %MART_NAME%.TEMP93 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='MOD';
drop table %MART_NAME%.TEMP93;
create table %MART_NAME%.TEMP95 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP94;
drop table %MART_NAME%.TEMP94;
create index I_105 on %MART_NAME%.TEMP95(accession_305);
create index I_106 on %MART_NAME%.TEMP95(accession_305_r1);
rename table %MART_NAME%.TEMP95 to %MART_NAME%.closure_MOD__closure__main;
create index I_107 on %MART_NAME%.closure_MOD__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP96 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_108 on %MART_NAME%.TEMP96(child_term_id_301);
create table %MART_NAME%.TEMP97 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP96 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP96;
create index I_109 on %MART_NAME%.TEMP97(ontology_id_305);
create table %MART_NAME%.TEMP98 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP97 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='OGMS';
drop table %MART_NAME%.TEMP97;
create index I_110 on %MART_NAME%.TEMP98(parent_term_id_301);
create table %MART_NAME%.TEMP99 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP98 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP98;
create index I_111 on %MART_NAME%.TEMP99(ontology_id_305_r1);
create table %MART_NAME%.TEMP100 as select a.* from %MART_NAME%.TEMP99 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='OGMS';
drop table %MART_NAME%.TEMP99;
create index I_112 on %MART_NAME%.TEMP100(subparent_term_id_301);
create table %MART_NAME%.TEMP101 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP100 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP100;
create index I_113 on %MART_NAME%.TEMP101(ontology_id_305_r2);
create table %MART_NAME%.TEMP102 as select a.* from %MART_NAME%.TEMP101 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='OGMS';
drop table %MART_NAME%.TEMP101;
create table %MART_NAME%.TEMP103 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP102;
drop table %MART_NAME%.TEMP102;
create index I_114 on %MART_NAME%.TEMP103(accession_305);
create index I_115 on %MART_NAME%.TEMP103(accession_305_r1);
rename table %MART_NAME%.TEMP103 to %MART_NAME%.closure_OGMS__closure__main;
create index I_116 on %MART_NAME%.closure_OGMS__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP104 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_117 on %MART_NAME%.TEMP104(child_term_id_301);
create table %MART_NAME%.TEMP105 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP104 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP104;
create index I_118 on %MART_NAME%.TEMP105(ontology_id_305);
create table %MART_NAME%.TEMP106 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP105 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PATO';
drop table %MART_NAME%.TEMP105;
create index I_119 on %MART_NAME%.TEMP106(parent_term_id_301);
create table %MART_NAME%.TEMP107 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP106 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP106;
create index I_120 on %MART_NAME%.TEMP107(ontology_id_305_r1);
create table %MART_NAME%.TEMP108 as select a.* from %MART_NAME%.TEMP107 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PATO';
drop table %MART_NAME%.TEMP107;
create index I_121 on %MART_NAME%.TEMP108(subparent_term_id_301);
create table %MART_NAME%.TEMP109 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP108 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP108;
create index I_122 on %MART_NAME%.TEMP109(ontology_id_305_r2);
create table %MART_NAME%.TEMP110 as select a.* from %MART_NAME%.TEMP109 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PATO';
drop table %MART_NAME%.TEMP109;
create table %MART_NAME%.TEMP111 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP110;
drop table %MART_NAME%.TEMP110;
create index I_123 on %MART_NAME%.TEMP111(accession_305);
create index I_124 on %MART_NAME%.TEMP111(accession_305_r1);
rename table %MART_NAME%.TEMP111 to %MART_NAME%.closure_PATO__closure__main;
create index I_125 on %MART_NAME%.closure_PATO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP112 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_126 on %MART_NAME%.TEMP112(child_term_id_301);
create table %MART_NAME%.TEMP113 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP112 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP112;
create index I_127 on %MART_NAME%.TEMP113(ontology_id_305);
create table %MART_NAME%.TEMP114 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP113 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PBO';
drop table %MART_NAME%.TEMP113;
create index I_128 on %MART_NAME%.TEMP114(parent_term_id_301);
create table %MART_NAME%.TEMP115 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP114 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP114;
create index I_129 on %MART_NAME%.TEMP115(ontology_id_305_r1);
create table %MART_NAME%.TEMP116 as select a.* from %MART_NAME%.TEMP115 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PBO';
drop table %MART_NAME%.TEMP115;
create index I_130 on %MART_NAME%.TEMP116(subparent_term_id_301);
create table %MART_NAME%.TEMP117 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP116 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP116;
create index I_131 on %MART_NAME%.TEMP117(ontology_id_305_r2);
create table %MART_NAME%.TEMP118 as select a.* from %MART_NAME%.TEMP117 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PBO';
drop table %MART_NAME%.TEMP117;
create table %MART_NAME%.TEMP119 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP118;
drop table %MART_NAME%.TEMP118;
create index I_132 on %MART_NAME%.TEMP119(accession_305);
create index I_133 on %MART_NAME%.TEMP119(accession_305_r1);
rename table %MART_NAME%.TEMP119 to %MART_NAME%.closure_PBO__closure__main;
create index I_134 on %MART_NAME%.closure_PBO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP120 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_135 on %MART_NAME%.TEMP120(child_term_id_301);
create table %MART_NAME%.TEMP121 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP120 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP120;
create index I_136 on %MART_NAME%.TEMP121(ontology_id_305);
create table %MART_NAME%.TEMP122 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP121 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PBQ';
drop table %MART_NAME%.TEMP121;
create index I_137 on %MART_NAME%.TEMP122(parent_term_id_301);
create table %MART_NAME%.TEMP123 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP122 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP122;
create index I_138 on %MART_NAME%.TEMP123(ontology_id_305_r1);
create table %MART_NAME%.TEMP124 as select a.* from %MART_NAME%.TEMP123 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PBQ';
drop table %MART_NAME%.TEMP123;
create index I_139 on %MART_NAME%.TEMP124(subparent_term_id_301);
create table %MART_NAME%.TEMP125 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP124 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP124;
create index I_140 on %MART_NAME%.TEMP125(ontology_id_305_r2);
create table %MART_NAME%.TEMP126 as select a.* from %MART_NAME%.TEMP125 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PBQ';
drop table %MART_NAME%.TEMP125;
create table %MART_NAME%.TEMP127 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP126;
drop table %MART_NAME%.TEMP126;
create index I_141 on %MART_NAME%.TEMP127(accession_305);
create index I_142 on %MART_NAME%.TEMP127(accession_305_r1);
rename table %MART_NAME%.TEMP127 to %MART_NAME%.closure_PBQ__closure__main;
create index I_143 on %MART_NAME%.closure_PBQ__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP128 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_144 on %MART_NAME%.TEMP128(child_term_id_301);
create table %MART_NAME%.TEMP129 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP128 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP128;
create index I_145 on %MART_NAME%.TEMP129(ontology_id_305);
create table %MART_NAME%.TEMP130 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP129 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PECO';
drop table %MART_NAME%.TEMP129;
create index I_146 on %MART_NAME%.TEMP130(parent_term_id_301);
create table %MART_NAME%.TEMP131 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP130 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP130;
create index I_147 on %MART_NAME%.TEMP131(ontology_id_305_r1);
create table %MART_NAME%.TEMP132 as select a.* from %MART_NAME%.TEMP131 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PECO';
drop table %MART_NAME%.TEMP131;
create index I_148 on %MART_NAME%.TEMP132(subparent_term_id_301);
create table %MART_NAME%.TEMP133 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP132 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP132;
create index I_149 on %MART_NAME%.TEMP133(ontology_id_305_r2);
create table %MART_NAME%.TEMP134 as select a.* from %MART_NAME%.TEMP133 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PECO';
drop table %MART_NAME%.TEMP133;
create table %MART_NAME%.TEMP135 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP134;
drop table %MART_NAME%.TEMP134;
create index I_150 on %MART_NAME%.TEMP135(accession_305);
create index I_151 on %MART_NAME%.TEMP135(accession_305_r1);
rename table %MART_NAME%.TEMP135 to %MART_NAME%.closure_PECO__closure__main;
create index I_152 on %MART_NAME%.closure_PECO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP136 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_153 on %MART_NAME%.TEMP136(child_term_id_301);
create table %MART_NAME%.TEMP137 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP136 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP136;
create index I_154 on %MART_NAME%.TEMP137(ontology_id_305);
create table %MART_NAME%.TEMP138 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP137 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PHI';
drop table %MART_NAME%.TEMP137;
create index I_155 on %MART_NAME%.TEMP138(parent_term_id_301);
create table %MART_NAME%.TEMP139 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP138 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP138;
create index I_156 on %MART_NAME%.TEMP139(ontology_id_305_r1);
create table %MART_NAME%.TEMP140 as select a.* from %MART_NAME%.TEMP139 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PHI';
drop table %MART_NAME%.TEMP139;
create index I_157 on %MART_NAME%.TEMP140(subparent_term_id_301);
create table %MART_NAME%.TEMP141 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP140 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP140;
create index I_158 on %MART_NAME%.TEMP141(ontology_id_305_r2);
create table %MART_NAME%.TEMP142 as select a.* from %MART_NAME%.TEMP141 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PHI';
drop table %MART_NAME%.TEMP141;
create table %MART_NAME%.TEMP143 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP142;
drop table %MART_NAME%.TEMP142;
create index I_159 on %MART_NAME%.TEMP143(accession_305);
create index I_160 on %MART_NAME%.TEMP143(accession_305_r1);
rename table %MART_NAME%.TEMP143 to %MART_NAME%.closure_PHI__closure__main;
create index I_161 on %MART_NAME%.closure_PHI__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP144 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_162 on %MART_NAME%.TEMP144(child_term_id_301);
create table %MART_NAME%.TEMP145 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP144 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP144;
create index I_163 on %MART_NAME%.TEMP145(ontology_id_305);
create table %MART_NAME%.TEMP146 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP145 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='PO';
drop table %MART_NAME%.TEMP145;
create index I_164 on %MART_NAME%.TEMP146(parent_term_id_301);
create table %MART_NAME%.TEMP147 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP146 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP146;
create index I_165 on %MART_NAME%.TEMP147(ontology_id_305_r1);
create table %MART_NAME%.TEMP148 as select a.* from %MART_NAME%.TEMP147 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='PO';
drop table %MART_NAME%.TEMP147;
create index I_166 on %MART_NAME%.TEMP148(subparent_term_id_301);
create table %MART_NAME%.TEMP149 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP148 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP148;
create index I_167 on %MART_NAME%.TEMP149(ontology_id_305_r2);
create table %MART_NAME%.TEMP150 as select a.* from %MART_NAME%.TEMP149 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='PO';
drop table %MART_NAME%.TEMP149;
create table %MART_NAME%.TEMP151 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP150;
drop table %MART_NAME%.TEMP150;
create index I_168 on %MART_NAME%.TEMP151(accession_305);
create index I_169 on %MART_NAME%.TEMP151(accession_305_r1);
rename table %MART_NAME%.TEMP151 to %MART_NAME%.closure_PO__closure__main;
create index I_170 on %MART_NAME%.closure_PO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP152 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_171 on %MART_NAME%.TEMP152(child_term_id_301);
create table %MART_NAME%.TEMP153 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP152 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP152;
create index I_172 on %MART_NAME%.TEMP153(ontology_id_305);
create table %MART_NAME%.TEMP154 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP153 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='SO';
drop table %MART_NAME%.TEMP153;
create index I_173 on %MART_NAME%.TEMP154(parent_term_id_301);
create table %MART_NAME%.TEMP155 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP154 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP154;
create index I_174 on %MART_NAME%.TEMP155(ontology_id_305_r1);
create table %MART_NAME%.TEMP156 as select a.* from %MART_NAME%.TEMP155 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='SO';
drop table %MART_NAME%.TEMP155;
create index I_175 on %MART_NAME%.TEMP156(subparent_term_id_301);
create table %MART_NAME%.TEMP157 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP156 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP156;
create index I_176 on %MART_NAME%.TEMP157(ontology_id_305_r2);
create table %MART_NAME%.TEMP158 as select a.* from %MART_NAME%.TEMP157 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='SO';
drop table %MART_NAME%.TEMP157;
create table %MART_NAME%.TEMP159 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP158;
drop table %MART_NAME%.TEMP158;
create index I_177 on %MART_NAME%.TEMP159(accession_305);
create index I_178 on %MART_NAME%.TEMP159(accession_305_r1);
rename table %MART_NAME%.TEMP159 to %MART_NAME%.closure_SO__closure__main;
create index I_179 on %MART_NAME%.closure_SO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP160 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_180 on %MART_NAME%.TEMP160(child_term_id_301);
create table %MART_NAME%.TEMP161 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP160 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP160;
create index I_181 on %MART_NAME%.TEMP161(ontology_id_305);
create table %MART_NAME%.TEMP162 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP161 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='TO';
drop table %MART_NAME%.TEMP161;
create index I_182 on %MART_NAME%.TEMP162(parent_term_id_301);
create table %MART_NAME%.TEMP163 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP162 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP162;
create index I_183 on %MART_NAME%.TEMP163(ontology_id_305_r1);
create table %MART_NAME%.TEMP164 as select a.* from %MART_NAME%.TEMP163 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='TO';
drop table %MART_NAME%.TEMP163;
create index I_184 on %MART_NAME%.TEMP164(subparent_term_id_301);
create table %MART_NAME%.TEMP165 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP164 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP164;
create index I_185 on %MART_NAME%.TEMP165(ontology_id_305_r2);
create table %MART_NAME%.TEMP166 as select a.* from %MART_NAME%.TEMP165 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='TO';
drop table %MART_NAME%.TEMP165;
create table %MART_NAME%.TEMP167 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP166;
drop table %MART_NAME%.TEMP166;
create index I_186 on %MART_NAME%.TEMP167(accession_305);
create index I_187 on %MART_NAME%.TEMP167(accession_305_r1);
rename table %MART_NAME%.TEMP167 to %MART_NAME%.closure_TO__closure__main;
create index I_188 on %MART_NAME%.closure_TO__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP168 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_189 on %MART_NAME%.TEMP168(child_term_id_301);
create table %MART_NAME%.TEMP169 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP168 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP168;
create index I_190 on %MART_NAME%.TEMP169(ontology_id_305);
create table %MART_NAME%.TEMP170 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP169 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='UNKNOWN';
drop table %MART_NAME%.TEMP169;
create index I_191 on %MART_NAME%.TEMP170(parent_term_id_301);
create table %MART_NAME%.TEMP171 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP170 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP170;
create index I_192 on %MART_NAME%.TEMP171(ontology_id_305_r1);
create table %MART_NAME%.TEMP172 as select a.* from %MART_NAME%.TEMP171 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='UNKNOWN';
drop table %MART_NAME%.TEMP171;
create index I_193 on %MART_NAME%.TEMP172(subparent_term_id_301);
create table %MART_NAME%.TEMP173 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP172 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP172;
create index I_194 on %MART_NAME%.TEMP173(ontology_id_305_r2);
create table %MART_NAME%.TEMP174 as select a.* from %MART_NAME%.TEMP173 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='UNKNOWN';
drop table %MART_NAME%.TEMP173;
create table %MART_NAME%.TEMP175 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP174;
drop table %MART_NAME%.TEMP174;
create index I_195 on %MART_NAME%.TEMP175(accession_305);
create index I_196 on %MART_NAME%.TEMP175(accession_305_r1);
rename table %MART_NAME%.TEMP175 to %MART_NAME%.closure_UNKNOWN__closure__main;
create index I_197 on %MART_NAME%.closure_UNKNOWN__closure__main(closure_id_301_key);
create table %MART_NAME%.TEMP176 as select a.parent_term_id as parent_term_id_301,a.distance as distance_301,a.subparent_term_id as subparent_term_id_301,a.child_term_id as child_term_id_301,a.closure_id as closure_id_301_key from %ONTOLOGY_DB%.closure as a;
create index I_198 on %MART_NAME%.TEMP176(child_term_id_301);
create table %MART_NAME%.TEMP177 as select a.*,b.ontology_id as ontology_id_305,b.name as name_305,b.definition as definition_305,b.accession as accession_305,b.subsets as subsets_305 from %MART_NAME%.TEMP176 as a inner join %ONTOLOGY_DB%.term as b on a.child_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP176;
create index I_199 on %MART_NAME%.TEMP177(ontology_id_305);
create table %MART_NAME%.TEMP178 as select a.*,b.name as name_302,b.namespace as namespace_302 from %MART_NAME%.TEMP177 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305=b.ontology_id and b.name='UO';
drop table %MART_NAME%.TEMP177;
create index I_200 on %MART_NAME%.TEMP178(parent_term_id_301);
create table %MART_NAME%.TEMP179 as select a.*,b.ontology_id as ontology_id_305_r1,b.name as name_305_r1,b.definition as definition_305_r1,b.accession as accession_305_r1,b.subsets as subsets_305_r1 from %MART_NAME%.TEMP178 as a inner join %ONTOLOGY_DB%.term as b on a.parent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP178;
create index I_201 on %MART_NAME%.TEMP179(ontology_id_305_r1);
create table %MART_NAME%.TEMP180 as select a.* from %MART_NAME%.TEMP179 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r1=b.ontology_id and b.name='UO';
drop table %MART_NAME%.TEMP179;
create index I_202 on %MART_NAME%.TEMP180(subparent_term_id_301);
create table %MART_NAME%.TEMP181 as select a.*,b.ontology_id as ontology_id_305_r2,b.accession as accession_305_r2,b.subsets as subsets_305_r2 from %MART_NAME%.TEMP180 as a left join %ONTOLOGY_DB%.term as b on a.subparent_term_id_301=b.term_id;
drop table %MART_NAME%.TEMP180;
create index I_203 on %MART_NAME%.TEMP181(ontology_id_305_r2);
create table %MART_NAME%.TEMP182 as select a.* from %MART_NAME%.TEMP181 as a left join %ONTOLOGY_DB%.ontology as b on a.ontology_id_305_r2=b.ontology_id and b.name='UO';
drop table %MART_NAME%.TEMP181;
create table %MART_NAME%.TEMP183 as select distinct accession_305_r1,accession_305_r2,subsets_305,definition_305_r1,accession_305,definition_305,closure_id_301_key,subsets_305_r2,subsets_305_r1,namespace_302,distance_301,name_302,name_305_r1,name_305 from %MART_NAME%.TEMP182;
drop table %MART_NAME%.TEMP182;
create index I_204 on %MART_NAME%.TEMP183(accession_305);
create index I_205 on %MART_NAME%.TEMP183(accession_305_r1);
rename table %MART_NAME%.TEMP183 to %MART_NAME%.closure_UO__closure__main;
create index I_206 on %MART_NAME%.closure_UO__closure__main(closure_id_301_key);
